spring:
  data:
    mongodb:
      host: ${MONGO_HOST}
      #username: ${MONGO_USER}
      #password: ${MONGO_PASSWORD}
      port: 27017
      repositories:
        enabled: true
      database: ${MONGO_DB}
  security:
    basic:
      enabled: false
    oauth2:
      client:
        client-id: virtualrooms
      resourceserver:
        jwt:
          jwk-set-uri: https://auth.youthclubstage.de/auth/realms/ycspublic/protocol/openid-connect/certs
management:
  endpoint:
    health:
      show-details: always
cors:
  allowedOrigins: '*'
  allowedHeaders:
    - Authorization
    - Content-Type
  exposedHeaders:
    - Authorization
    - Content-Type
logging:
  level:
    root: WARN
    org.springframework.security.oauth2: DEBUG